config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
  resources :users
  resources :players, only: [:show]
  resources :player_teams
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  get '/schedule', to: 'seasons#schedule', as: 'schedule'
  get '/list_teams', to: 'seasons#list_teams', as: 'list_teams'
  get '/standings', to: 'seasons#standings', as: 'standings'
  get '/statistics', to: 'seasons#statistics', as: 'statistics'


  # resources :games

  resources :seasons, shallow: true do
    resources :games
    resources :teams, only: [:edit]
  end
end

app/models/season.rb
class Season < ApplicationRecord
  has_many :player_seasons, dependent: :nullify
  has_many :players, through: :player_seasons, source: :player
  has_many :teams, inverse_of: :season, dependent: :nullify
  has_many :games, inverse_of: :season, dependent: :nullify
  accepts_nested_attributes_for :games, allow_destroy: true
  accepts_nested_attributes_for :teams, allow_destroy: true


  validates :name, presence: {message: 'Please Enter a Name'},
                    uniqueness: { case_sensitive: false,
                                  message: 'must be unique' }

  validates :teams, presence: true

end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController

  before_action :find_season, only: [:edit, :update, :destroy, :show]
  def new
    @season = Season.new
    @team = Team.new
  end

  def create
    @season = Season.new season_params
    if @season.save
      redirect_to edit_season_path(@season), notice: 'Season Created'
    else
      puts @season.errors.full_messages.join(', ')
      flash.now[:alert] = 'Please see errors below'
      render :new
    end
  end

  def edit
  end

  def update
    if @season.update season_params
      redirect_to root_path, notice: 'Season Created'
    else
      puts @season.errors.full_messages.join(', ')
      flash.now[:alert] = 'Please see errors below'
      redirect_to new_season_path( @season)
    end
  end

  def show
    @game = Game.new
    respond_to do |format|
      format.html { render }
      format.json { render json: @season.to_json }
  end
  end

  def destroy
  end

  def index
    @seasons = Season.all
    if params[:game] && (params[:game][:season_id] != '')
      @games = Game.where(season_id: params[:game][:season_id])
      @season = Season.find(params[:game][:season_id])
    else
      @games = Game.where(season: current_season)
      @season = current_season
    end
  end


  def schedule
    if params[:game] && (params[:game][:season_id] != '')
      @season = Season.find(params[:game][:season_id])
    else
      @games = Game.where(season: current_season)
      @season = current_season
    end
  end

  def standings
    if params[:team] && (params[:team][:season_id] != '')
      @season = Season.find(params[:team][:season_id])
    else
      @teams = Team.where(season: current_season)
      @season = current_season
    end
  end

  def statistics
    @seasons = Season.all
    if params[:player] && (params[:player][:season_id] != '')
      @player_seasons = PlayerSeason.where(season_id: params[:player][:season_id])
      @players = @player_seasons.map(&:player)
      @season = Season.find(params[:player][:season_id])
    else
      @player_seasons = PlayerSeason.where(season: current_season)
      @players = @player_seasons.map(&:player)
      @season = current_season
    end
  end

  def list_teams
    if params[:team] && (params[:team][:season_id] != '')
      @season = Season.find(params[:team][:season_id])
    else
      @teams = Team.where(season: current_season)
      @season = current_season
  end
end
  private

    def season_params
      params.require(:season).permit(:name,
                                      games_attributes: [:id, :date,
                                                         :home_team_id,
                                                         :away_team_id,
                                                         :_destroy],
                                      teams_attributes: [:id, :name, :avatar,
                                                                    :_destroy])
    end

    def find_season
      @season = Season.find params[:id]
    end

end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/seasons/_game_fields.html.erb
<div class='nested-fields'> <div> <%= f.datetime_select :date,  :minute_step => 15, :ampm => true %> </div>
<div> <%= f.association :home_team, collection: Team.order(:name)%> </div>
<div> <%= f.association :away_team, collection: Team.order(:name)%> </div>

 <%= link_to_remove_association "remove game", f %>

</div>

app/views/seasons/_game_form.html.erb
<div class="col-xs-12">
  <%# adding the `remote: true` option makes the form submit with jQuery
      using the jquery_ujs library inlucded in the manifest file by
      default and it will prevent default submission for the form as well
      so it's going to use preventDefault() under the hood %>
  <%= form_for [@season ,@game], remote: true do |f| %>
    <div class="form-group">
     <div> <%= f.datetime_select :date,  :minute_step => 15, :ampm => true %> </div>
      <div> <%= f.collection_select(:home_team_id, Team.where(season_id: @season.id), :id, :name, {:prompt => 'Home Team'}) %> </div>
      <div> <%= f.collection_select(:away_team_id, Team.where(season_id: @season.id), :id, :name, {:prompt => 'Away Team'}) %> </div>
    </div>
    <%= f.submit class: "btn btn-default" %>
  <% end %>
  <hr/>
</div>

app/views/seasons/_team_fields.html.erb
<div class='nested-fields'>
  <%= f.input :name %>
  <%= f.file_field :avatar %>
  <%= link_to_remove_association "remove team", f %>
</div>

app/views/seasons/edit.html.erb
<%= simple_form_for @season do |f| %>
  <h3>Games</h3>
  <div>
    <%= f.simple_fields_for :games do |game| %>
      <%= render 'game_fields', :f => game %>
    <% end %>
    <div>
      <%= link_to_add_association 'add game', f, :games %>
    </div>
  </div>
  <%= f.button :submit %>
<% end %>


<% @season.games.each do |g| %>
<div id='game_<%=g.id %>'>
  <%= link_to g.date.strftime('%A, %d %b %Y %l:%M %p'), game_path(g) %>
  <%= link_to g.home_team.name, game_path(g) %>
  <%= link_to g.away_team.name, game_path(g) %>
  <%= link_to game_path(g),
                    method: :delete,
                    remote: true,
                    data: { confirm: 'are you sure?' },
                    class: "pull-right" do %>
          <span class="glyphicon glyphicon-trash"></span>
        <% end %>
      <hr>
  </div>

<% end %>

app/views/seasons/index.html.erb
Select Which Season you would like to edit the Schedule of:


<% @seasons.each do |s| %>
  <div>
    <%= link_to s.name, season_path(s) %>
  </div>
<% end %>

app/views/seasons/list_teams.html.erb
<div class="w3-padding-large w3-padding-64" id="main">
<%if Team.exists?%>
<%= form_tag list_teams_path, :method => 'get' do %>
  <%= collection_select :team, :season_id, Season.order(name: :desc), :id, :name, prompt: @season.name, class:"team-filter" %>
  <%= submit_tag 'Filter' %>
<% end %>
<hr>
<div class="team__list">
<% @season.teams.each do |t|%>
  <%# link_to edit_team_path(t) do %>
    <%# image_tag t.avatar.url(:medium) %>
  <%# end %>
  <div class="team__name">
    <%= link_to t.name, edit_team_path(t) %>
  </div>
<% end %>
</div>
<% else %>
There are no teams
<% end %>
</div>

app/views/seasons/new.html.erb
<div class="w3-padding-large">
  <div class="w3-content w3-justify w3-text-grey w3-padding-64">

  <%= simple_form_for @season do |f| %>
    <%= f.input :name %>
    <h3>Teams</h3>
    <div class="form-group">
      <%= f.simple_fields_for :teams do |team| %>
        <%= render 'team_fields', :f => team %>
      <% end %>
      <div class='links'>
        <%= link_to_add_association 'add team', f, :teams %>
      </div>
    </div>
    <%= f.submit 'Save' %>
  <% end %>
  </div>
</div>

app/views/seasons/schedule.html.erb
<div class="w3-padding-large">
  <div class="w3-content w3-justify w3-text-grey w3-padding-64">

<%= form_tag schedule_path, :method => 'get' do %>
  <%= collection_select :game, :season_id, Season.order(name: :desc), :id, :name, prompt: @season.name %>
  <%= submit_tag 'Filter' %>
<% end %>
<hr>

<%# @season.teams.each do |t|%>
  <%# image_tag t.avatar.url(:medium) %>
<%# end %>

  <% @season.games.each do |g| %>
      <div>
        <%= link_to g.date.strftime('%A, %d %b %Y %l:%M %p'), game_path(g) %>
        <%= link_to g.home_team.name, game_path(g) %>
        <%= link_to g.away_team.name, game_path(g) %>
      </div>
  <% end %>
</div>
</div>

app/views/seasons/show.html.erb
<div>
  <div id='game-form'>
    <%= render 'games/game_form' %>
  </div>
<div id='games'>
    <% @season.games.each do |game| %>
        <div>
          <%= render('games/game', { season: @season, g: game }) %>
        </div>
    <% end %>
  </div>
</div>

app/views/seasons/standings.html.erb
<div class="w3-padding-large w3-padding-64" id="main">
<%if Team.exists?%>
<%= form_tag standings_path, :method => 'get' do %>
  <%= collection_select :team, :season_id, Season.order(name: :desc), :id, :name, prompt: @season.name, class:"team-filter" %>
  <%= submit_tag 'Filter' %>
<% end %>
<hr>
<div class="team__list">
<% @season.teams.each do |t|%>
  <%# link_to edit_team_path(t) do %>
    <%# image_tag t.avatar.url(:medium) %>
  <%# end %>
  <div class="team__name">
    <%= link_to t.name, edit_team_path(t) %>
    <%= t.games_played(@season) %>
    <%= t.regulation_wins(@season) %>
    <%= t.overtime_wins(@season) %>
    <%= t.regulation_losses(@season) %>
    <%= t.points(@season) %>
  </div>
<% end %>
</div>
<% else %>
There are no teams
<% end %>
</div>

app/views/seasons/statistics.html.erb
<div class="w3-padding-large w3-padding-64" id="main">
<%if Team.exists?%>
<%= form_tag statistics_path, :method => 'get' do %>
  <%= collection_select :player, :season_id, Season.order(name: :desc), :id, :name, prompt: @season.name, class:"team-filter" %>
  <%= submit_tag 'Filter' %>
<% end %>
<hr>
<div class="team_list">
<% @players.each do |p|%>
  <%= p.first_name + ' ' + p.last_name %>

  <%# link_to edit_team_path(t) do %>
    <%# image_tag t.avatar.url(:medium) %>
  <%# end %>

<% end %>
</div>
<% else %>
There are no teams
<% end %>
</div>