config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
  resources :users
  resources :players, only: [:show]
  resources :player_teams
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  get '/schedule', to: 'seasons#schedule', as: 'schedule'
  get '/list_teams', to: 'seasons#list_teams', as: 'list_teams'
  get '/standings', to: 'seasons#standings', as: 'standings'
  get '/statistics', to: 'seasons#statistics', as: 'statistics'


  # resources :games

  resources :seasons, shallow: true do
    resources :games
    resources :teams, only: [:edit]
  end
end

app/models/game.rb
class Game < ApplicationRecord

  belongs_to :home_team, :class_name => "Team"
  belongs_to :away_team, :class_name => "Team"
  belongs_to :winning_team, :class_name => "Team"
  belongs_to :losing_team, :class_name => "Team"

  belongs_to :season, inverse_of: :games

  has_many :goals, dependent: :destroy
  accepts_nested_attributes_for :goals, :allow_destroy => true

  has_many :assists, dependent: :destroy
  accepts_nested_attributes_for :assists, :allow_destroy => true


  has_many :players, through: :player_games, source: :player
  has_many :player_games, dependent: :destroy

  validates :date, presence: true,
                    uniqueness: true



    include AASM
    aasm whiny_transitions: false do
      state :scheduled, initial: true
      state :played
      state :canceled

      event :play do
        transitions from: :scheduled, to: :played
      end

      event :cancel do
        transitions from: :scheduled, to: :canceled
      end

      event :replay do
        transitions from: :played, to: :scheduled
      end

    end


end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  before_action :find_game, except: [:new, :create, :index]

  def new
    @game = Game.new
  end

  def create
    @game = Game.new game_params
    @game.season = Season.find(params[:season_id])
    respond_to do |format|
      if @game.save
        format.js { render :success }
        format.html do
          redirect_to game_path(@game), notice: 'Game created!'
        end
      else
        format.js { render :create_failure }
      end
    end
  end


  def index
    if params[:game] && (params[:game][:season_id] != '')
      @games = Game.where(season_id: params[:game][:season_id])
      @season = Season.find(params[:game][:season_id])
    else
      @games = Game.where(season: current_season)
      @season = current_season
    end
  end

  def show
    @goals = Goal.where(game: @game)
    @home_team_goals = Goal.where(game: @game, team: @game.home_team)
    @away_team_goals = Goal.where(game: @game, team: @game.away_team)
  end

  def destroy
    @game = Game.find params[:id]
    respond_to do |format|
        season = @game.season
        @game.destroy
        format.html { redirect_to seasons_path, notice: 'Game deleted!' }
        format.js   { render } # destroy.js.erb
      end
    end

  def edit
    @home_team = @game.home_team
    @away_team = @game.away_team
  end

  def update
    if @game.update game_params
      if @game.goals.exists? && @game
        @game.play
        @game.save
      end
    end
      flash[:notice] = 'Game updated'
      redirect_to game_path(@game)
    else
      flash.now[:alert] = 'Please see errors below!'
      render :edit
    end
  end

  private

  def game_params
    params.require(:game).permit([:id,
                                  :date,
                                  :season_id,
                                  :home_team_id,
                                  :away_team_id,
          goals_attributes: [:id, :team_id, :player_id, :_destroy,
          assists_attributes: [:id,:team_id,:player_id, :goal_id, :_destroy]
                                                                            ]])
  end

  def find_game
      @game = Game.find params[:id]
    end

end

app/views/games/_assist_fields.html.erb
<span class='nested-fields'>
  <div>
    <%= f.collection_select(:player_id, @game.home_team.players.all, :id, :full_name, {:prompt => 'Assist'}) %>
  </div>
  <%= f.hidden_field :team_id, value: @game.home_team.id %>
  <%= link_to_remove_association "remove assist", f %>
</span>

app/views/games/_game.html.erb
<div id='game_<%=g.id %>'>  
  <%= link_to g.date.strftime('%A, %d %b %Y %l:%M %p'), game_path(g) %>
  <%= link_to g.home_team.name, game_path(g) %>
  <%= link_to g.away_team.name, game_path(g) %>
  <%= link_to game_path(g),
                    method: :delete,
                    remote: true,
                    data: { confirm: 'are you sure?' },
                    class: "pull-right" do %>
          <span class="glyphicon glyphicon-trash"></span>
        <% end %>
</div>

app/views/games/_game_form.html.erb
  <%= form_for [@season, @game], remote: true do |f| %>

     <div> <%= f.datetime_select :date, :minute_step => 15, prompt: true %> </div>
      <div> <%= f.collection_select(:home_team_id, Team.all, :id, :name, {:prompt => 'Home Team'}) %> </div>
      <div> <%= f.collection_select(:away_team_id, Team.all, :id, :name, {:prompt => 'Away Team'}) %> </div>

    <%= f.submit class: "btn btn-default" %>
  <% end %>
  <hr/>

app/views/games/_goal_fields.html.erb
<div class='nested-fields'>
  <div> <%= f.collection_select(:player_id, @game.home_team.players.all, :id, :full_name, {:prompt => 'Goal Scorer'}) %> </div>
  <%= f.hidden_field :team_id, value: @game.home_team.id %>
  <%= f.simple_fields_for :assists do |assist| %>
    <%= render 'assist_fields', f: assist %>
  <% end %>
  <div>
    <%= link_to_add_association 'add assist', f, :assists %>
  </div>  <%= link_to_remove_association "remove goal", f %>
</div>

app/views/games/create_failure.js.erb
$('#game-form').prepend('<div id ="error"> Please Add a Valid Date and Two Different Teams</div>');
$('#error').hide();
$('#error').css('color','red');
$('#error').fadeIn('slow');

app/views/games/destroy.js.erb
$("#<%= dom_id(@game) %>").fadeOut(800, function(){ $(this).remove(); });

<%= puts dom_id(@game) %>

app/views/games/edit.html.erb
<div class="w3-padding-large">
  <div class="w3-content w3-justify w3-text-grey w3-padding-64">
    <div class='home-team-game-form'>
      <%= simple_form_for @game do |f| %>
        <%= f.simple_fields_for :goals do |goal| %>
          <%= render 'goal_fields', f: goal, g: @game %>
        <% end %>
        <div>
          <%= link_to_add_association 'add goal', f, :goals %>
        </div>
      <%= f.button :submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/games/index.html.erb
<%= form_tag games_path, :method => 'get' do %>
  <%= collection_select :game, :season_id, Season.order(name: :desc), :id, :name, prompt: @season.name %>
  <%= submit_tag 'Filter' %>
<% end %>
<hr>

<% @games.each do |g| %>
  <%= link_to g.date.strftime('%A, %d %b %Y %l:%M %p'), game_path(g) %>
  <%= link_to g.home_team.name, game_path(g) %>
  <%= link_to g.away_team.name, game_path(g) %>
  <hr>
<% end %>

app/views/games/new.html.erb
<%= @game.errors.full_messages.join(', ') %>


<%= simple_form_for @game, html: { class: 'form-vertical' } do |f| %>

    <div class="dropdown">
        <%= f.association :season, collection: Season.order(:name) %>
    </div>

    <div class="dropdown">
      <%= f.datetime_select :date,  :minute_step => 15, :ampm => true %>
    </div>

    <div class="dropdown">
      <%= f.association :home_team, collection: Team.order(:name)%>
    </div>

    <div class="dropdown">
      <%= f.association :away_team, collection: Team.order(:name)%>
    </div>



    <div class="submit">
        <%= f.submit "Submit" %>
    </div>
<% end %>

app/views/games/show.html.erb
<div class="w3-padding-large">
  <div class="w3-content w3-justify w3-text-grey w3-padding-64">
    <% if @game.scheduled? %>
      <h1> <%= @game.date.strftime('%A, %d %b %Y %l:%M %p') %>: - </h1>
      <h1> <%= @game.home_team.name %>: - </h1>
      <h1> <%= @game.away_team.name %>: - </h1>
    <% elsif @game.played? %>
      <div> Final </div>
      <h1> <%= @game.home_team.name %>: <%= @home_team_goals.count %></h1>
      <h1> <%= @game.away_team.name %>: <%= @away_team_goals.count %> </h1>
    <% end %>
    <%= link_to 'Edit Game', edit_game_path(@game) %>
  </div>
</div>

app/views/games/success.js.erb
$('#games').prepend("<%= j render 'game', g: @game %>");
$('#game_<%=@game.id%>').hide().slideDown();