config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
  resources :users
  resources :players, only: [:show]
  resources :player_teams
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  get '/schedule', to: 'seasons#schedule', as: 'schedule'
  get '/list_teams', to: 'seasons#list_teams', as: 'list_teams'
  get '/standings', to: 'seasons#standings', as: 'standings'
  get '/statistics', to: 'seasons#statistics', as: 'statistics'


  # resources :games

  resources :seasons, shallow: true do
    resources :games
    resources :teams, only: [:edit]
  end
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :assists
  accepts_nested_attributes_for :assists, :allow_destroy => true

  has_many :goals
  accepts_nested_attributes_for :goals, :allow_destroy => true


  has_many :player_teams, dependent: :nullify
  has_many :teams_played_for, through: :player_teams, source: :team

  has_many :player_games, dependent: :nullify
  has_many :games_played_by_player, through: :player_games, source: :game

  has_many :player_seasons, dependent: :nullify
  has_many :seasons, through: :player_seasons, source: :season

  belongs_to :user, :foreign_key => 'user_id'

  def full_name
    first_name + ' ' + last_name
  end


  def add_season (s)
    player_seasons.create(season_id: s.id)
  end

  def add_game (g)
    player_games.create(game_id: g.id)
  end

  def add_team (t)
    player_teams.create(team_id: t.id)
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController



end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_player.html.erb
<div id='player_<%=p.id %>'>
  <%= link_to p.full_name, player_path(p) %>


  <%= link_to player_team_path(pt),
                    method: :delete,
                    remote: true,
                    data: { confirm: 'are you sure?' },
                    class: "pull-right" do %>
          <span class="glyphicon glyphicon-trash"></span>
        <% end %>
</div>

app/views/players/player.html.erb
<div id='player<%=p.id %>'>  
  <%= link_to g.date.strftime('%A, %d %b %Y %l:%M %p'), game_path(g) %>
  <%= link_to g.home_team.name, game_path(g) %>
  <%= link_to g.away_team.name, game_path(g) %>
  <%= link_to game_path(g),
                    method: :delete,
                    remote: true,
                    data: { confirm: 'are you sure?' },
                    class: "pull-right" do %>
          <span class="glyphicon glyphicon-trash"></span>
        <% end %>
</div>